### ISSUE TITLE
Errors when deploying quickstart-polly-ccp

### ISSUE THREAD

**Issue by randymontz** [aws-quickstart/quickstart-poly-ccp#5]
It would seem when we run the template, it tries to copy some files from the source s3 bucket to one in our account and either the source bucket does not allow access to copy or has missing objects which this template is looking to copy over.

I should state we are deploying with no domain. We are just entering the instance alais

![image](https://user-images.githubusercontent.com/80786607/111369160-1a8df400-866d-11eb-831e-327dda016752.png)

Any Advice

**Comment by Yukinori-Shimizu** [comment]
I have the same issue and stack deployment fails.

**Comment by davmayd** [comment]
@randymontz @Yukinori-Shimizu there was a dependency on an S3 bucket hosted by Poly, which is no longer public. The dependency has been updated and the stack now deploys successfully.

**Comment by davmayd** [comment]
https://github.com/aws-quickstart/quickstart-poly-ccp/commit/b37e7415b0c8668875692a262197f9d07219df2f
